### ISSUE TITLE
Hostile doesn't remove entries where one IP is mapped to two domains

### ISSUE THREAD

**Issue by sahil1610** [feross/hostile#31]
/etc/hosts
192.178.176.1 test1.com test2.com

If I am calling `hostile.remove(192.178.176.1, 'test1.com test2.com')` from my node code, then the host file entry is not removed.

**Comment by feross** [comment]
Works for me.

**Comment by feross** [comment]
It's not possible to debug this issue without additional information. If this is still an issue, please leave a comment or open a new issue.

**Comment by josephfusco** [comment]
@sahil1610 Any solution for this? I am running into the same issue.
