### ISSUE TITLE
Example using sudo

### ISSUE THREAD

**Issue by pruett** [feross/hostile#33]
Is there an example of a node script that calls `hostile` using `sudo`? I've tried `child_process.spawn()` without success. Do you know of a way to achieve this without manually configuring OS files (`chmod`, etc.). Thanks

**Comment by unilynx** [comment]
Default sudo configuration often require passwords and have the 'requiretty' option set (at least some linux distros do that). Are you sure those are disabled ? Both will break sudo.

With that fixed, I've succesfully invoked sudo hostile this way:
```
  console.log("Launching sudo hostile set " + machineinfo.ipv4 + " " + hostinfo.getName());
  child_process.spawnSync('sudo', ['hostile', 'set', machineinfo.ipv4, hostinfo.getName() ],{ stdio: ['ignore',1,2] });
```

**Comment by pruett** [comment]
great, thanks!
